sudo: required
services:
  - docker

before_install:
  - docker build -t sylphile/docker-react -f Dockerfile.dev Dockerfile.dev .

script:
  - docker run sylphile/docker-react npm run test -- --coverage
  